/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CollectorRouteImport } from './routes/collector'
import { Route as CollectorIndexRouteImport } from './routes/collector.index'
import { Route as CollectorEarningsRouteImport } from './routes/collector.earnings'
import { Route as CollectorLotsRouteImport } from './routes/collector.lots'
import { Route as CollectorNotificationsRouteImport } from './routes/collector.notifications'
import { Route as CollectorPricesRouteImport } from './routes/collector.prices'
import { Route as CollectorRecyclersRouteImport } from './routes/collector.recyclers'
import { Route as CollectorSafetyRouteImport } from './routes/collector.safety'
import { Route as CollectorScanRouteImport } from './routes/collector.scan'
import { Route as CollectorHandoverLotIdRouteImport } from './routes/collector.handover.$lotId'
import { Route as CollectorLotLotIdRouteImport } from './routes/collector.lot.$lotId'
import { Route as CollectorPaymentLotIdRouteImport } from './routes/collector.payment.$lotId'
import { Route as CollectorReceiptLotIdRouteImport } from './routes/collector.receipt.$lotId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorRoute = CollectorRouteImport.update({
  id: '/collector',
  path: '/collector',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorIndexRoute = CollectorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorEarningsRoute = CollectorEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorLotsRoute = CollectorLotsRouteImport.update({
  id: '/lots',
  path: '/lots',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorNotificationsRoute = CollectorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorPricesRoute = CollectorPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorRecyclersRoute = CollectorRecyclersRouteImport.update({
  id: '/recyclers',
  path: '/recyclers',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorSafetyRoute = CollectorSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorScanRoute = CollectorScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorHandoverLotIdRoute = CollectorHandoverLotIdRouteImport.update({
  id: '/handover/$lotId',
  path: '/handover/$lotId',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorLotLotIdRoute = CollectorLotLotIdRouteImport.update({
  id: '/lot/$lotId',
  path: '/lot/$lotId',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorPaymentLotIdRoute = CollectorPaymentLotIdRouteImport.update({
  id: '/payment/$lotId',
  path: '/payment/$lotId',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorReceiptLotIdRoute = CollectorReceiptLotIdRouteImport.update({
  id: '/receipt/$lotId',
  path: '/receipt/$lotId',
  getParentRoute: () => CollectorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collector': typeof CollectorRouteWithChildren
  '/collector/earnings': typeof CollectorEarningsRoute
  '/collector/lots': typeof CollectorLotsRoute
  '/collector/notifications': typeof CollectorNotificationsRoute
  '/collector/prices': typeof CollectorPricesRoute
  '/collector/recyclers': typeof CollectorRecyclersRoute
  '/collector/safety': typeof CollectorSafetyRoute
  '/collector/scan': typeof CollectorScanRoute
  '/collector/': typeof CollectorIndexRoute
  '/collector/handover/$lotId': typeof CollectorHandoverLotIdRoute
  '/collector/lot/$lotId': typeof CollectorLotLotIdRoute
  '/collector/payment/$lotId': typeof CollectorPaymentLotIdRoute
  '/collector/receipt/$lotId': typeof CollectorReceiptLotIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collector/earnings': typeof CollectorEarningsRoute
  '/collector/lots': typeof CollectorLotsRoute
  '/collector/notifications': typeof CollectorNotificationsRoute
  '/collector/prices': typeof CollectorPricesRoute
  '/collector/recyclers': typeof CollectorRecyclersRoute
  '/collector/safety': typeof CollectorSafetyRoute
  '/collector/scan': typeof CollectorScanRoute
  '/collector': typeof CollectorIndexRoute
  '/collector/handover/$lotId': typeof CollectorHandoverLotIdRoute
  '/collector/lot/$lotId': typeof CollectorLotLotIdRoute
  '/collector/payment/$lotId': typeof CollectorPaymentLotIdRoute
  '/collector/receipt/$lotId': typeof CollectorReceiptLotIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collector': typeof CollectorRouteWithChildren
  '/collector/earnings': typeof CollectorEarningsRoute
  '/collector/lots': typeof CollectorLotsRoute
  '/collector/notifications': typeof CollectorNotificationsRoute
  '/collector/prices': typeof CollectorPricesRoute
  '/collector/recyclers': typeof CollectorRecyclersRoute
  '/collector/safety': typeof CollectorSafetyRoute
  '/collector/scan': typeof CollectorScanRoute
  '/collector/': typeof CollectorIndexRoute
  '/collector/handover/$lotId': typeof CollectorHandoverLotIdRoute
  '/collector/lot/$lotId': typeof CollectorLotLotIdRoute
  '/collector/payment/$lotId': typeof CollectorPaymentLotIdRoute
  '/collector/receipt/$lotId': typeof CollectorReceiptLotIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/collector'
    | '/collector/earnings'
    | '/collector/lots'
    | '/collector/notifications'
    | '/collector/prices'
    | '/collector/recyclers'
    | '/collector/safety'
    | '/collector/scan'
    | '/collector/'
    | '/collector/handover/$lotId'
    | '/collector/lot/$lotId'
    | '/collector/payment/$lotId'
    | '/collector/receipt/$lotId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/collector/earnings'
    | '/collector/lots'
    | '/collector/notifications'
    | '/collector/prices'
    | '/collector/recyclers'
    | '/collector/safety'
    | '/collector/scan'
    | '/collector'
    | '/collector/handover/$lotId'
    | '/collector/lot/$lotId'
    | '/collector/payment/$lotId'
    | '/collector/receipt/$lotId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/collector'
    | '/collector/earnings'
    | '/collector/lots'
    | '/collector/notifications'
    | '/collector/prices'
    | '/collector/recyclers'
    | '/collector/safety'
    | '/collector/scan'
    | '/collector/'
    | '/collector/handover/$lotId'
    | '/collector/lot/$lotId'
    | '/collector/payment/$lotId'
    | '/collector/receipt/$lotId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CollectorRoute: typeof CollectorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector': {
      id: '/collector'
      path: '/collector'
      fullPath: '/collector'
      preLoaderRoute: typeof CollectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector/': {
      id: '/collector/'
      path: '/'
      fullPath: '/collector/'
      preLoaderRoute: typeof CollectorIndexRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/earnings': {
      id: '/collector/earnings'
      path: '/earnings'
      fullPath: '/collector/earnings'
      preLoaderRoute: typeof CollectorEarningsRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/lots': {
      id: '/collector/lots'
      path: '/lots'
      fullPath: '/collector/lots'
      preLoaderRoute: typeof CollectorLotsRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/notifications': {
      id: '/collector/notifications'
      path: '/notifications'
      fullPath: '/collector/notifications'
      preLoaderRoute: typeof CollectorNotificationsRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/prices': {
      id: '/collector/prices'
      path: '/prices'
      fullPath: '/collector/prices'
      preLoaderRoute: typeof CollectorPricesRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/recyclers': {
      id: '/collector/recyclers'
      path: '/recyclers'
      fullPath: '/collector/recyclers'
      preLoaderRoute: typeof CollectorRecyclersRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/safety': {
      id: '/collector/safety'
      path: '/safety'
      fullPath: '/collector/safety'
      preLoaderRoute: typeof CollectorSafetyRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/scan': {
      id: '/collector/scan'
      path: '/scan'
      fullPath: '/collector/scan'
      preLoaderRoute: typeof CollectorScanRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/handover/$lotId': {
      id: '/collector/handover/$lotId'
      path: '/handover/$lotId'
      fullPath: '/collector/handover/$lotId'
      preLoaderRoute: typeof CollectorHandoverLotIdRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/lot/$lotId': {
      id: '/collector/lot/$lotId'
      path: '/lot/$lotId'
      fullPath: '/collector/lot/$lotId'
      preLoaderRoute: typeof CollectorLotLotIdRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/payment/$lotId': {
      id: '/collector/payment/$lotId'
      path: '/payment/$lotId'
      fullPath: '/collector/payment/$lotId'
      preLoaderRoute: typeof CollectorPaymentLotIdRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/receipt/$lotId': {
      id: '/collector/receipt/$lotId'
      path: '/receipt/$lotId'
      fullPath: '/collector/receipt/$lotId'
      preLoaderRoute: typeof CollectorReceiptLotIdRouteImport
      parentRoute: typeof CollectorRoute
    }
  }
}

interface CollectorRouteChildren {
  CollectorEarningsRoute: typeof CollectorEarningsRoute
  CollectorLotsRoute: typeof CollectorLotsRoute
  CollectorNotificationsRoute: typeof CollectorNotificationsRoute
  CollectorPricesRoute: typeof CollectorPricesRoute
  CollectorRecyclersRoute: typeof CollectorRecyclersRoute
  CollectorSafetyRoute: typeof CollectorSafetyRoute
  CollectorScanRoute: typeof CollectorScanRoute
  CollectorIndexRoute: typeof CollectorIndexRoute
  CollectorHandoverLotIdRoute: typeof CollectorHandoverLotIdRoute
  CollectorLotLotIdRoute: typeof CollectorLotLotIdRoute
  CollectorPaymentLotIdRoute: typeof CollectorPaymentLotIdRoute
  CollectorReceiptLotIdRoute: typeof CollectorReceiptLotIdRoute
}

const CollectorRouteChildren: CollectorRouteChildren = {
  CollectorEarningsRoute: CollectorEarningsRoute,
  CollectorLotsRoute: CollectorLotsRoute,
  CollectorNotificationsRoute: CollectorNotificationsRoute,
  CollectorPricesRoute: CollectorPricesRoute,
  CollectorRecyclersRoute: CollectorRecyclersRoute,
  CollectorSafetyRoute: CollectorSafetyRoute,
  CollectorScanRoute: CollectorScanRoute,
  CollectorIndexRoute: CollectorIndexRoute,
  CollectorHandoverLotIdRoute: CollectorHandoverLotIdRoute,
  CollectorLotLotIdRoute: CollectorLotLotIdRoute,
  CollectorPaymentLotIdRoute: CollectorPaymentLotIdRoute,
  CollectorReceiptLotIdRoute: CollectorReceiptLotIdRoute,
}

const CollectorRouteWithChildren = CollectorRoute._addFileChildren(
  CollectorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CollectorRoute: CollectorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
